# Generated by Django 4.1.3 on 2025-03-04 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Lodging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=280)),
                ('image', models.URLField()),
                ('link', models.URLField(blank=True, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_created', to='saltandearthapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('description', models.CharField(max_length=280)),
                ('link', models.URLField(blank=True, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_created', to='saltandearthapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=280)),
                ('uid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_tags', to='saltandearthapp.restaurant')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='saltandearthapp.tag')),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='saltandearthapp.user'),
        ),
        migrations.CreateModel(
            name='LodgingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_tags', to='saltandearthapp.lodging')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgings', to='saltandearthapp.tag')),
            ],
        ),
        migrations.AddField(
            model_name='lodging',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging', to='saltandearthapp.user'),
        ),
    ]
