# Generated by Django 4.1.3 on 2025-03-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saltandearthapp', '0002_lodging_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='uid',
            field=models.CharField(default='default_uid', max_length=50),
            preserve_default=False,
        ),
    ]
