# Generated by Django 4.2.16 on 2025-03-05 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saltandearthapp', '0003_restaurant_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lodgingtag',
            old_name='lodging_id',
            new_name='lodging',
        ),
        migrations.RenameField(
            model_name='lodgingtag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
