# Generated by Django 4.2.16 on 2025-03-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saltandearthapp', '0004_rename_lodging_id_lodgingtag_lodging_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauranttag',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='restauranttag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
